# Docker Compose configuration for local development
# This setup uses local .NET execution with containerized SQL Server
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "${ACCEPT_EULA}"
      SA_PASSWORD: "${SA_PASSWORD}"
      MSSQL_PID: "${MSSQL_PID}"
    ports:
      - "${MSSQL_PORT}:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -C -Q 'SELECT 1' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - modelibr

volumes:
  mssql-data:

networks:
  modelibr:
    driver: bridge