// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.ApplicationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CleanRecycledFilesAfterDays")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GenerateThumbnailOnUpload")
                        .HasColumnType("boolean");

                    b.Property<long>("MaxFileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxThumbnailSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TextureProxySize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(512);

                    b.Property<double>("ThumbnailCameraVerticalAngle")
                        .HasColumnType("double precision");

                    b.Property<int>("ThumbnailFrameCount")
                        .HasColumnType("integer");

                    b.Property<int>("ThumbnailHeight")
                        .HasColumnType("integer");

                    b.Property<int>("ThumbnailWidth")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSettings");
                });

            modelBuilder.Entity("Domain.Models.BatchUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("EnvironmentMapId")
                        .HasColumnType("integer");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModelId")
                        .HasColumnType("integer");

                    b.Property<int?>("PackId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("SoundId")
                        .HasColumnType("integer");

                    b.Property<int?>("SpriteId")
                        .HasColumnType("integer");

                    b.Property<int?>("TextureSetId")
                        .HasColumnType("integer");

                    b.Property<string>("UploadType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("EnvironmentMapId");

                    b.HasIndex("FileId");

                    b.HasIndex("ModelId");

                    b.HasIndex("PackId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SoundId");

                    b.HasIndex("SpriteId");

                    b.HasIndex("TextureSetId");

                    b.HasIndex("UploadType");

                    b.HasIndex("UploadedAt");

                    b.ToTable("BatchUploads");
                });

            modelBuilder.Entity("Domain.Models.EnvironmentMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomThumbnailFileId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EnvironmentMapCategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PreviewVariantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomThumbnailFileId");

                    b.HasIndex("EnvironmentMapCategoryId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.ToTable("EnvironmentMaps");
                });

            modelBuilder.Entity("Domain.Models.EnvironmentMapCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.ToTable("EnvironmentMapCategories");
                });

            modelBuilder.Entity("Domain.Models.EnvironmentMapVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnvironmentMapId")
                        .HasColumnType("integer");

                    b.Property<int?>("FileId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProjectionType")
                        .HasColumnType("integer");

                    b.Property<string>("SizeLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("EnvironmentMapId", "SizeLabel")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("EnvironmentMapVariants");
                });

            modelBuilder.Entity("Domain.Models.EnvironmentMapVariantFaceFile", b =>
                {
                    b.Property<int>("EnvironmentMapVariantId")
                        .HasColumnType("integer");

                    b.Property<int>("Face")
                        .HasColumnType("integer");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.HasKey("EnvironmentMapVariantId", "Face");

                    b.HasIndex("FileId");

                    b.ToTable("EnvironmentMapVariantFaceFiles");
                });

            modelBuilder.Entity("Domain.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ModelVersionId")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModelVersionId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Domain.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveVersionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("FileId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ModelCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActiveVersionId")
                        .IsUnique();

                    b.HasIndex("FileId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModelCategoryId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Models_UpdatedAt");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("Domain.Models.ModelCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.ToTable("ModelCategories");
                });

            modelBuilder.Entity("Domain.Models.ModelConceptImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("ModelId", "FileId")
                        .IsUnique();

                    b.HasIndex("ModelId", "SortOrder");

                    b.ToTable("ModelConceptImages");
                });

            modelBuilder.Entity("Domain.Models.ModelTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("ModelTags", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ModelVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultTextureSetId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MainVariantName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("MaterialCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("MaterialNames")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<int?>("MeshCount")
                        .HasColumnType("integer");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TechnicalDetailsUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ThumbnailId")
                        .HasColumnType("integer");

                    b.Property<int?>("TriangleCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("VariantNames")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("VertexCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DefaultTextureSetId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ThumbnailId")
                        .IsUnique();

                    b.HasIndex("ModelId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ModelVersions");
                });

            modelBuilder.Entity("Domain.Models.ModelVersionTextureSet", b =>
                {
                    b.Property<int>("ModelVersionId")
                        .HasColumnType("integer");

                    b.Property<int>("TextureSetId")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("");

                    b.Property<string>("VariantName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("");

                    b.HasKey("ModelVersionId", "TextureSetId", "MaterialName", "VariantName");

                    b.HasIndex("TextureSetId");

                    b.ToTable("ModelVersionTextureSets", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Pack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomThumbnailFileId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LicenseType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CustomThumbnailFileId");

                    b.HasIndex("LicenseType");

                    b.HasIndex("Name");

                    b.ToTable("Packs");
                });

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomThumbnailFileId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomThumbnailFileId");

                    b.HasIndex("Name");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Domain.Models.ProjectConceptImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("ProjectId", "FileId")
                        .IsUnique();

                    b.HasIndex("ProjectId", "SortOrder");

                    b.ToTable("ProjectConceptImages");
                });

            modelBuilder.Entity("Domain.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Domain.Models.Sound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Duration")
                        .HasColumnType("double precision");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Peaks")
                        .HasColumnType("text");

                    b.Property<int?>("SoundCategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("SoundCategoryId");

                    b.ToTable("Sounds");
                });

            modelBuilder.Entity("Domain.Models.SoundCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.ToTable("SoundCategories");
                });

            modelBuilder.Entity("Domain.Models.Sprite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("SpriteCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("SpriteType")
                        .HasColumnType("integer");

                    b.Property<int?>("ThumbnailId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("SpriteCategoryId");

                    b.HasIndex("ThumbnailId");

                    b.ToTable("Sprites");
                });

            modelBuilder.Entity("Domain.Models.SpriteCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.ToTable("SpriteCategories");
                });

            modelBuilder.Entity("Domain.Models.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("Domain.Models.Texture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SourceChannel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<int?>("TextureSetId")
                        .HasColumnType("integer");

                    b.Property<int>("TextureType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("TextureType");

                    b.HasIndex("TextureSetId", "TextureType")
                        .HasFilter("\"TextureSetId\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("TextureSetId", "FileId", "SourceChannel")
                        .IsUnique()
                        .HasFilter("\"TextureSetId\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.ToTable("Textures");
                });

            modelBuilder.Entity("Domain.Models.TextureProxy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("TextureId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("TextureId");

                    b.HasIndex("TextureId", "Size")
                        .IsUnique();

                    b.ToTable("TextureProxies");
                });

            modelBuilder.Entity("Domain.Models.TextureSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PngThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PreviewGeometryType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("plane");

                    b.Property<int?>("TextureSetCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<float>("TilingScaleX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.Property<float>("TilingScaleY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UvMappingMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<float>("UvScale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1f);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Kind");

                    b.HasIndex("Name");

                    b.HasIndex("TextureSetCategoryId");

                    b.ToTable("TextureSets");
                });

            modelBuilder.Entity("Domain.Models.TextureSetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.ToTable("TextureSetCategories");
                });

            modelBuilder.Entity("Domain.Models.Thumbnail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<int>("ModelVersionId")
                        .HasColumnType("integer");

                    b.Property<string>("PngThumbnailPath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModelVersionId")
                        .IsUnique();

                    b.ToTable("Thumbnails");
                });

            modelBuilder.Entity("Domain.Models.ThumbnailJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EnvironmentMapId")
                        .HasColumnType("integer");

                    b.Property<int?>("EnvironmentMapVariantId")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("LockTimeoutMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("ModelHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("ModelId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModelVersionId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProxySize")
                        .HasColumnType("integer");

                    b.Property<string>("SoundHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("SoundId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TextureSetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentMapId");

                    b.HasIndex("EnvironmentMapVariantId")
                        .IsUnique()
                        .HasFilter("\"EnvironmentMapVariantId\" IS NOT NULL");

                    b.HasIndex("ModelId");

                    b.HasIndex("ModelVersionId");

                    b.HasIndex("SoundHash")
                        .IsUnique()
                        .HasFilter("[SoundHash] IS NOT NULL");

                    b.HasIndex("SoundId");

                    b.HasIndex("TextureSetId");

                    b.HasIndex("ModelHash", "ModelVersionId")
                        .IsUnique()
                        .HasFilter("[ModelHash] IS NOT NULL AND [ModelVersionId] IS NOT NULL");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("ThumbnailJobs");
                });

            modelBuilder.Entity("Domain.Models.ThumbnailJobEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ThumbnailJobId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ThumbnailJobId", "OccurredAt");

                    b.ToTable("ThumbnailJobEvents");
                });

            modelBuilder.Entity("EnvironmentMapPack", b =>
                {
                    b.Property<int>("EnvironmentMapsId")
                        .HasColumnType("integer");

                    b.Property<int>("PacksId")
                        .HasColumnType("integer");

                    b.HasKey("EnvironmentMapsId", "PacksId");

                    b.HasIndex("PacksId");

                    b.ToTable("PackEnvironmentMaps", (string)null);
                });

            modelBuilder.Entity("EnvironmentMapProject", b =>
                {
                    b.Property<int>("EnvironmentMapsId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("integer");

                    b.HasKey("EnvironmentMapsId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("ProjectEnvironmentMaps", (string)null);
                });

            modelBuilder.Entity("EnvironmentMapTagAssignment", b =>
                {
                    b.Property<int>("EnvironmentMapId")
                        .HasColumnType("integer");

                    b.Property<int>("ModelTagId")
                        .HasColumnType("integer");

                    b.HasKey("EnvironmentMapId", "ModelTagId");

                    b.HasIndex("ModelTagId");

                    b.ToTable("EnvironmentMapTagAssignments", (string)null);
                });

            modelBuilder.Entity("ModelPack", b =>
                {
                    b.Property<int>("ModelsId")
                        .HasColumnType("integer");

                    b.Property<int>("PacksId")
                        .HasColumnType("integer");

                    b.HasKey("ModelsId", "PacksId");

                    b.HasIndex("PacksId");

                    b.ToTable("PackModels", (string)null);
                });

            modelBuilder.Entity("ModelProject", b =>
                {
                    b.Property<int>("ModelsId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectsId")
                        .HasColumnType("integer");

                    b.HasKey("ModelsId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("ProjectModels", (string)null);
                });

            modelBuilder.Entity("ModelTagAssignment", b =>
                {
                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<int>("ModelTagId")
                        .HasColumnType("integer");

                    b.HasKey("ModelId", "ModelTagId");

                    b.HasIndex("ModelTagId");

                    b.ToTable("ModelTagAssignments", (string)null);
                });

            modelBuilder.Entity("ModelTextureSet", b =>
                {
                    b.Property<int>("ModelsId")
                        .HasColumnType("integer");

                    b.Property<int>("TextureSetsId")
                        .HasColumnType("integer");

                    b.HasKey("ModelsId", "TextureSetsId");

                    b.HasIndex("TextureSetsId");

                    b.ToTable("ModelTextureSets", (string)null);
                });

            modelBuilder.Entity("PackSound", b =>
                {
                    b.Property<int>("PacksId")
                        .HasColumnType("integer");

                    b.Property<int>("SoundsId")
                        .HasColumnType("integer");

                    b.HasKey("PacksId", "SoundsId");

                    b.HasIndex("SoundsId");

                    b.ToTable("PackSounds", (string)null);
                });

            modelBuilder.Entity("PackSprite", b =>
                {
                    b.Property<int>("PacksId")
                        .HasColumnType("integer");

                    b.Property<int>("SpritesId")
                        .HasColumnType("integer");

                    b.HasKey("PacksId", "SpritesId");

                    b.HasIndex("SpritesId");

                    b.ToTable("PackSprites", (string)null);
                });

            modelBuilder.Entity("PackTextureSet", b =>
                {
                    b.Property<int>("PacksId")
                        .HasColumnType("integer");

                    b.Property<int>("TextureSetsId")
                        .HasColumnType("integer");

                    b.HasKey("PacksId", "TextureSetsId");

                    b.HasIndex("TextureSetsId");

                    b.ToTable("PackTextureSets", (string)null);
                });

            modelBuilder.Entity("ProjectSound", b =>
                {
                    b.Property<int>("ProjectsId")
                        .HasColumnType("integer");

                    b.Property<int>("SoundsId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectsId", "SoundsId");

                    b.HasIndex("SoundsId");

                    b.ToTable("ProjectSounds", (string)null);
                });

            modelBuilder.Entity("ProjectSprite", b =>
                {
                    b.Property<int>("ProjectsId")
                        .HasColumnType("integer");

                    b.Property<int>("SpritesId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectsId", "SpritesId");

                    b.HasIndex("SpritesId");

                    b.ToTable("ProjectSprites", (string)null);
                });

            modelBuilder.Entity("ProjectTextureSet", b =>
                {
                    b.Property<int>("ProjectsId")
                        .HasColumnType("integer");

                    b.Property<int>("TextureSetsId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectsId", "TextureSetsId");

                    b.HasIndex("TextureSetsId");

                    b.ToTable("ProjectTextureSets", (string)null);
                });

            modelBuilder.Entity("Domain.Models.BatchUpload", b =>
                {
                    b.HasOne("Domain.Models.EnvironmentMap", "EnvironmentMap")
                        .WithMany()
                        .HasForeignKey("EnvironmentMapId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.Pack", "Pack")
                        .WithMany()
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.Sound", "Sound")
                        .WithMany()
                        .HasForeignKey("SoundId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.Sprite", "Sprite")
                        .WithMany()
                        .HasForeignKey("SpriteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.TextureSet", "TextureSet")
                        .WithMany()
                        .HasForeignKey("TextureSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EnvironmentMap");

                    b.Navigation("File");

                    b.Navigation("Model");

                    b.Navigation("Pack");

                    b.Navigation("Project");

                    b.Navigation("Sound");

                    b.Navigation("Sprite");

                    b.Navigation("TextureSet");
                });

            modelBuilder.Entity("Domain.Models.EnvironmentMap", b =>
                {
                    b.HasOne("Domain.Models.File", "CustomThumbnailFile")
                        .WithMany()
                        .HasForeignKey("CustomThumbnailFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.EnvironmentMapCategory", "EnvironmentMapCategory")
                        .WithMany()
                        .HasForeignKey("EnvironmentMapCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CustomThumbnailFile");

                    b.Navigation("EnvironmentMapCategory");
                });

            modelBuilder.Entity("Domain.Models.EnvironmentMapCategory", b =>
                {
                    b.HasOne("Domain.Models.EnvironmentMapCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Models.EnvironmentMapVariant", b =>
                {
                    b.HasOne("Domain.Models.EnvironmentMap", null)
                        .WithMany("Variants")
                        .HasForeignKey("EnvironmentMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("File");
                });

            modelBuilder.Entity("Domain.Models.EnvironmentMapVariantFaceFile", b =>
                {
                    b.HasOne("Domain.Models.EnvironmentMapVariant", null)
                        .WithMany("FaceFiles")
                        .HasForeignKey("EnvironmentMapVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Domain.Models.File", b =>
                {
                    b.HasOne("Domain.Models.ModelVersion", "ModelVersion")
                        .WithMany("Files")
                        .HasForeignKey("ModelVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ModelVersion");
                });

            modelBuilder.Entity("Domain.Models.Model", b =>
                {
                    b.HasOne("Domain.Models.ModelVersion", "ActiveVersion")
                        .WithOne()
                        .HasForeignKey("Domain.Models.Model", "ActiveVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Models.File", null)
                        .WithMany("Models")
                        .HasForeignKey("FileId");

                    b.HasOne("Domain.Models.ModelCategory", "ModelCategory")
                        .WithMany()
                        .HasForeignKey("ModelCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveVersion");

                    b.Navigation("ModelCategory");
                });

            modelBuilder.Entity("Domain.Models.ModelCategory", b =>
                {
                    b.HasOne("Domain.Models.ModelCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Models.ModelConceptImage", b =>
                {
                    b.HasOne("Domain.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Model", "Model")
                        .WithMany("ConceptImages")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Domain.Models.ModelVersion", b =>
                {
                    b.HasOne("Domain.Models.TextureSet", null)
                        .WithMany()
                        .HasForeignKey("DefaultTextureSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.Model", "Model")
                        .WithMany("Versions")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Thumbnail", "Thumbnail")
                        .WithOne("ModelVersion")
                        .HasForeignKey("Domain.Models.ModelVersion", "ThumbnailId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Model");

                    b.Navigation("Thumbnail");
                });

            modelBuilder.Entity("Domain.Models.ModelVersionTextureSet", b =>
                {
                    b.HasOne("Domain.Models.ModelVersion", "ModelVersion")
                        .WithMany("TextureMappings")
                        .HasForeignKey("ModelVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.TextureSet", "TextureSet")
                        .WithMany("ModelVersionMappings")
                        .HasForeignKey("TextureSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelVersion");

                    b.Navigation("TextureSet");
                });

            modelBuilder.Entity("Domain.Models.Pack", b =>
                {
                    b.HasOne("Domain.Models.File", "CustomThumbnailFile")
                        .WithMany()
                        .HasForeignKey("CustomThumbnailFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CustomThumbnailFile");
                });

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.HasOne("Domain.Models.File", "CustomThumbnailFile")
                        .WithMany()
                        .HasForeignKey("CustomThumbnailFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CustomThumbnailFile");
                });

            modelBuilder.Entity("Domain.Models.ProjectConceptImage", b =>
                {
                    b.HasOne("Domain.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Project", "Project")
                        .WithMany("ConceptImages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Models.Sound", b =>
                {
                    b.HasOne("Domain.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.SoundCategory", "Category")
                        .WithMany()
                        .HasForeignKey("SoundCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Domain.Models.SoundCategory", b =>
                {
                    b.HasOne("Domain.Models.SoundCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Models.Sprite", b =>
                {
                    b.HasOne("Domain.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.SpriteCategory", "Category")
                        .WithMany()
                        .HasForeignKey("SpriteCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Models.Thumbnail", "Thumbnail")
                        .WithMany()
                        .HasForeignKey("ThumbnailId");

                    b.Navigation("Category");

                    b.Navigation("File");

                    b.Navigation("Thumbnail");
                });

            modelBuilder.Entity("Domain.Models.SpriteCategory", b =>
                {
                    b.HasOne("Domain.Models.SpriteCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Models.Texture", b =>
                {
                    b.HasOne("Domain.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.TextureSet", null)
                        .WithMany("Textures")
                        .HasForeignKey("TextureSetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("File");
                });

            modelBuilder.Entity("Domain.Models.TextureProxy", b =>
                {
                    b.HasOne("Domain.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Texture", "Texture")
                        .WithMany("Proxies")
                        .HasForeignKey("TextureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Texture");
                });

            modelBuilder.Entity("Domain.Models.TextureSet", b =>
                {
                    b.HasOne("Domain.Models.TextureSetCategory", "Category")
                        .WithMany()
                        .HasForeignKey("TextureSetCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Models.TextureSetCategory", b =>
                {
                    b.HasOne("Domain.Models.TextureSetCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Models.ThumbnailJob", b =>
                {
                    b.HasOne("Domain.Models.EnvironmentMap", "EnvironmentMap")
                        .WithMany()
                        .HasForeignKey("EnvironmentMapId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.EnvironmentMapVariant", "EnvironmentMapVariant")
                        .WithMany()
                        .HasForeignKey("EnvironmentMapVariantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.ModelVersion", "ModelVersion")
                        .WithMany()
                        .HasForeignKey("ModelVersionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.Sound", "Sound")
                        .WithMany()
                        .HasForeignKey("SoundId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.TextureSet", "TextureSet")
                        .WithMany()
                        .HasForeignKey("TextureSetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("EnvironmentMap");

                    b.Navigation("EnvironmentMapVariant");

                    b.Navigation("Model");

                    b.Navigation("ModelVersion");

                    b.Navigation("Sound");

                    b.Navigation("TextureSet");
                });

            modelBuilder.Entity("Domain.Models.ThumbnailJobEvent", b =>
                {
                    b.HasOne("Domain.Models.ThumbnailJob", "ThumbnailJob")
                        .WithMany()
                        .HasForeignKey("ThumbnailJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThumbnailJob");
                });

            modelBuilder.Entity("EnvironmentMapPack", b =>
                {
                    b.HasOne("Domain.Models.EnvironmentMap", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentMapsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Pack", null)
                        .WithMany()
                        .HasForeignKey("PacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnvironmentMapProject", b =>
                {
                    b.HasOne("Domain.Models.EnvironmentMap", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentMapsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnvironmentMapTagAssignment", b =>
                {
                    b.HasOne("Domain.Models.EnvironmentMap", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.ModelTag", null)
                        .WithMany()
                        .HasForeignKey("ModelTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModelPack", b =>
                {
                    b.HasOne("Domain.Models.Model", null)
                        .WithMany()
                        .HasForeignKey("ModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Pack", null)
                        .WithMany()
                        .HasForeignKey("PacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModelProject", b =>
                {
                    b.HasOne("Domain.Models.Model", null)
                        .WithMany()
                        .HasForeignKey("ModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModelTagAssignment", b =>
                {
                    b.HasOne("Domain.Models.Model", null)
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.ModelTag", null)
                        .WithMany()
                        .HasForeignKey("ModelTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModelTextureSet", b =>
                {
                    b.HasOne("Domain.Models.Model", null)
                        .WithMany()
                        .HasForeignKey("ModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.TextureSet", null)
                        .WithMany()
                        .HasForeignKey("TextureSetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PackSound", b =>
                {
                    b.HasOne("Domain.Models.Pack", null)
                        .WithMany()
                        .HasForeignKey("PacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Sound", null)
                        .WithMany()
                        .HasForeignKey("SoundsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PackSprite", b =>
                {
                    b.HasOne("Domain.Models.Pack", null)
                        .WithMany()
                        .HasForeignKey("PacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Sprite", null)
                        .WithMany()
                        .HasForeignKey("SpritesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PackTextureSet", b =>
                {
                    b.HasOne("Domain.Models.Pack", null)
                        .WithMany()
                        .HasForeignKey("PacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.TextureSet", null)
                        .WithMany()
                        .HasForeignKey("TextureSetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectSound", b =>
                {
                    b.HasOne("Domain.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Sound", null)
                        .WithMany()
                        .HasForeignKey("SoundsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectSprite", b =>
                {
                    b.HasOne("Domain.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Sprite", null)
                        .WithMany()
                        .HasForeignKey("SpritesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectTextureSet", b =>
                {
                    b.HasOne("Domain.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.TextureSet", null)
                        .WithMany()
                        .HasForeignKey("TextureSetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.EnvironmentMap", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Domain.Models.EnvironmentMapCategory", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Domain.Models.EnvironmentMapVariant", b =>
                {
                    b.Navigation("FaceFiles");
                });

            modelBuilder.Entity("Domain.Models.File", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Domain.Models.Model", b =>
                {
                    b.Navigation("ConceptImages");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Domain.Models.ModelCategory", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Domain.Models.ModelVersion", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("TextureMappings");
                });

            modelBuilder.Entity("Domain.Models.Project", b =>
                {
                    b.Navigation("ConceptImages");
                });

            modelBuilder.Entity("Domain.Models.SoundCategory", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Domain.Models.SpriteCategory", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Domain.Models.Texture", b =>
                {
                    b.Navigation("Proxies");
                });

            modelBuilder.Entity("Domain.Models.TextureSet", b =>
                {
                    b.Navigation("ModelVersionMappings");

                    b.Navigation("Textures");
                });

            modelBuilder.Entity("Domain.Models.TextureSetCategory", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Domain.Models.Thumbnail", b =>
                {
                    b.Navigation("ModelVersion")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
